# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=20, unique=True)),
                ('password', models.CharField(max_length=20, unique=True)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=20)),
                ('avatarImageUrl', models.ImageField(max_length=256, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('testTextFinished', models.TextField(max_length=600)),
                ('traslaterId', models.IntegerField()),
                ('scores', models.IntegerField()),
                ('price', models.IntegerField()),
                ('submissionFileUrl', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskId', models.IntegerField()),
                ('assignmentId', models.IntegerField()),
                ('employerStatement', models.CharField(max_length=300)),
                ('translaterStatement', models.CharField(max_length=300)),
                ('status', models.IntegerField()),
                ('adminStatement', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=20, unique=True)),
                ('password', models.CharField(max_length=20, unique=True)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=20)),
                ('avatarImageUrl', models.ImageField(max_length=256, upload_to='')),
                ('level', models.IntegerField()),
                ('experienceNumber', models.IntegerField()),
                ('alipayNumber', models.CharField(max_length=30)),
                ('wechatNumber', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languageType', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenseType', models.IntegerField()),
                ('licenseImage', models.ImageField(max_length=256, upload_to='')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=100, unique=True)),
                ('fileUrl', models.FilePathField(max_length=256)),
                ('fileType', models.IntegerField()),
                ('employerId', models.IntegerField()),
                ('publishTime', models.DateTimeField()),
                ('ddlTime', models.DateTimeField()),
                ('tags', models.CharField(max_length=128)),
                ('language', models.IntegerField()),
                ('requirementsLicense', models.IntegerField()),
                ('requirementsLevel', models.IntegerField()),
                ('testText', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Translater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=20, unique=True)),
                ('password', models.CharField(max_length=20, unique=True)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=20)),
                ('avatarImageUrl', models.ImageField(max_length=256, upload_to='')),
                ('level', models.IntegerField()),
                ('alipayNumber', models.CharField(max_length=30)),
                ('wechatNumber', models.CharField(max_length=30)),
                ('experienceNumber', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='license',
            name='belonger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Translater'),
        ),
        migrations.AddField(
            model_name='language',
            name='translaterId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Translater'),
        ),
    ]
