# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='testResult',
        ),
        migrations.AddField(
            model_name='assignment',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='testResult',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
