# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='translator',
            name='level',
            field=models.IntegerField(null=True),
        ),
    ]
