# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20180103_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='description',
        ),
        migrations.AlterField(
            model_name='license',
            name='licenseImage',
            field=models.ImageField(max_length=256, null=True, upload_to=''),
        ),
    ]
