# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20171208_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='requirementCreditLevel',
            field=models.FloatField(null=True),
        ),
    ]
