# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20180104_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='TranslatorId',
            new_name='translators',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='task',
            new_name='tasks',
        ),
    ]
